name: test custom
on: push

jobs:
  test-custom-action:
    runs-on: ubuntu-latest
    steps:
      - name: "checkout repo"
        uses: actions/checkout@v3
      - name: Hello world action step
        id: hello
        uses: /.github/actions/hello
        with:
          who-to-greet: "Poweres"
        # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
