name: CI
on:
  pull_request:
  push:
    branches:
      - "dev"
      - "master"
jobs:
  setup-repo:
    runs-on: ubuntu-latest
    steps:
      - name: "checkout repo"
        uses: actions/checkout@v3
      - name: "set upnode"
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-build-again-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-again
            ${{ runner.os }}-
      - name: install node module
        if: steps.cache-npm.outputs.cache-hit != 'true'
        run: npm ci

  run-test:
    runs-on: ubuntu-latest
    needs: [setup-repo]
    steps:
      - name: "checkout repo"
        uses: actions/checkout@v3
      - name: "set up node"
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-build-again-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-again
            ${{ runner.os }}-

      - name: "run test"
        continue-on-error: true
        env:
          CI: true
        run: npm run test -- --coverage

      - name: "upload report file"
        uses: actions/upload-artifact@v3
        with:
          name: "test-report"
          path: coverage
      - name: upload to codecov
        if: github.event_name == 'push' &&  github.ref == 'refs/heads/master'
        run: npx codecov
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}

  deploy-release:
    if: github.event_name == 'push' && (github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/master' )
    runs-on: ubuntu-latest
    needs: [run-test]
    steps:
      - name: "checkout repo"
        uses: actions/checkout@v3
      - name: "set upnode"
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-build-again-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-again
            ${{ runner.os }}-

      - name: "build website"
        run: npm run build

      - name: "upload build file"
        uses: actions/upload-artifact@v3
        with:
          name: "build"
          path: build

      - name: "select url for deploy"
        id: select-url
        run: |
          if [ "${{github.ref}}" = "refs/heads/dev" ]; then
            echo "::set-output name=url::righteous-grade111.surge.sh"
          else
            echo "::set-output name=url::annoyed-gold.surge.sh"
          fi
      - name: show which url
        run: echo ${{steps.select-url.outputs.url}}

      - name: Deploy to to surge
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: "${{ steps.select-url.outputs.url }}"
          project: "build"
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}
      - name: create release
        if: github.ref == 'refs/heads/master'
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
