name: CI
on:
  pull_request:
  push:
    branches:
      - "dev"
jobs:
  PR:
    runs-on: ubuntu-latest
    steps:
      - name: "checkout repo"
        uses: actions/checkout@v3
      - name: "set upnode"
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: install node module if not Cache
        if: steps.cache-npm.outputs.cache-hit != 'true'
        run: npm ci

      - name: "run test"
        continue-on-error: true
        env:
          CI: true
        run: npm run test -- --coverage
      - name: "show path"
        run: |
          pwd
          ls -a
      - uses: actions/upload-artifact@v3
        with:
          name: "test-report"
          path: coverage
