name: CI
on:
  pull_request:
  push:
    branches:
      - "dev"
jobs:
  setup-repo:
    runs-on: ubuntu-latest
    steps:
      - name: "checkout repo"
        uses: actions/checkout@v3
      - name: "set upnode"
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-build-again-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-again
            ${{ runner.os }}-
      - name: install node module
        run: npm ci

  run-test:
    runs-on: ubuntu-latest
    needs: [setup-repo]
    steps:
      - name: "checkout repo"
        uses: actions/checkout@v3
      - name: "set upnode"
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        with:
          path: |
            node_modules
             ~/.npm
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: "run test"
        continue-on-error: true
        env:
          CI: true
        run: npm run test -- --coverage

      - name: "upload report file"
        uses: actions/upload-artifact@v3
        with:
          name: "test-report"
          path: coverage

  deploy-ewbsite:
    if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    needs: [setup-repo]
    steps:
      - name: "checkout repo"
        uses: actions/checkout@v3
      - name: "set upnode"
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        with:
          path: |
            node_modules
             ~/.npm
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: "build website"
        run: npm run build

      - name: "upload build file"
        uses: actions/upload-artifact@v3
        with:
          name: "build"
          path: build

      - name: Deploy to righteous-grade111.surge.sh
        uses: dswistowski/surge-sh-action@v1

        with:
          domain: "righteous-grade111.surge.sh"
          project: "build"
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}
